#!/bin/sh

for i in scheme-*.tex; do
  echo "$i > post-$i"
  perl -pne '
    s/\\\$/\$/g;
    s/\\\_/\_/g;
    s/\\ensuremath{\\backslash}/\\/g;
    s#(node(?:\[\S+\])? at \(\d+\.\d+\\du,)(\d+\.\d+)(\\du)#$1.($2-0.25).$3#e;
  ' $i > post-$i
done
